app/controllers/login_controller.py
from flask import (
    Blueprint,
    render_template,
    request,
    current_app,
    session,
    redirect,
    url_for,
)

import requests
import jwt
from flask_login import (
    UserMixin,
    login_user,
    logout_user,
    current_user,
)
from jwt.exceptions import ExpiredSignatureError, InvalidTokenError
from app.models.db_models import Users  # Import your Users model
from app.models import db  # Import your SQLAlchemy database instance

login_controller = Blueprint("login_controller", __name__)


class User(UserMixin):
    def __init__(self, id, email, name):
        self.id = id
        self.email = email
        self.name = name


@login_controller.route("/login")
def login():
    """Redirect the user to Cognito's Hosted UI for authentication."""
    return redirect(current_app.config["COGNITO_HOSTED_LOGIN_URL"])


@login_controller.route("/callback")
def callback():
    """
    Handle the redirect from the Cognito Hosted UI.
    Extract the token from the URL fragment and validate it.
    """
    token = request.args.get("id_token")
    print(f"Token received: {token}")
    if token:
        _, status_code = decode_cognito_token(token)
        if status_code == 200:
            print(session)
            session["access_token"] = token

            # Log user in
            user_id = session["user_id"]
            # user_email = session["email"]
            user_name = session["name"]

            # Insert or update the user in the RDS database
            existing_user = Users.query.filter_by(user_id=user_id).first()
            if not existing_user:
                # Insert new user
                new_user = Users(user_id=user_id, user_name=user_name)
                db.session.add(new_user)
                print(f"New user added: {user_name}")
            else:
                # Update existing user's name (if needed)
                if existing_user.user_name != user_name:
                    existing_user.user_name = user_name
                    print(f"User updated: {user_name}")

            db.session.commit()  # Save changes to the database

            # Log user in
            user = User(
                id=session["user_id"], email=session["email"], name=session["name"]
            )
            login_user(user)
            return redirect(url_for("main_controller.open_dashboard"))

    return render_template("callback.html")


@login_controller.route("/logout")
def logout():
    """Log out the user by clearing the session and redirecting to the landing page."""
    session.clear()
    logout_user()
    return redirect(url_for("main_controller.index"))


def decode_cognito_token(token):
    try:

        # Fetch the public keys from Cognito
        jwk_url = f"https://cognito-idp.{current_app.config['COGNITO_REGION']}.amazonaws.com/{current_app.config['COGNITO_USERPOOL_ID']}/.well-known/jwks.json"
        response = requests.get(jwk_url)
        jwks = response.json()

        # Get the 'kid' from the token header
        headers = jwt.get_unverified_header(token)
        kid = headers["kid"]

        # Find the matching key
        key = next(k for k in jwks["keys"] if k["kid"] == kid)

        # Convert JWK to public key
        public_key = jwt.algorithms.RSAAlgorithm.from_jwk(key)

        # Decode and verify the token
        decoded_token = jwt.decode(
            token,
            public_key,
            algorithms=["RS256"],
            audience=current_app.config["COGNITO_APP_CLIENT_ID"],
        )
        # print(f"Decoded Token: {decoded_token}")
        user_id = decoded_token.get("sub")
        email = decoded_token.get("email")
        name = decoded_token.get("name")

        session["user_id"] = user_id
        session["email"] = email
        session["name"] = name
        return "Token decoded successfully", 200
    except ExpiredSignatureError:
        return "The token has expired", 401
    except InvalidTokenError as e:
        return f"Invalid token: {str(e)}", 401
    except Exception as e:
        return f"An error occurred: {str(e)}", 500


@login_controller.route("/home")
def home():
    if current_user.is_authenticated:
        if "access_token" in session:
            return redirect(url_for("main_controller.open_dashboard"))

    return redirect(url_for("login_controller.login"))

app/controllers/main_controller.py
from flask import Blueprint, render_template
from app.services.main_service import MainService

main_controller = Blueprint("main_controller", __name__)


@main_controller.route("/")
def index():
    message = MainService().get_message()
    return render_template("index.html", message=message)


@main_controller.route("/status")
# @login_required
def status():
    message = MainService().get_message(
        "The auction system is live and responding to requests!"
    )
    return render_template("index.html", message=message)


# Dashboard route
@main_controller.route("/dashboard")
# @login_required
def open_dashboard():
    return render_template("dashboard.html")

app/templates/shared/footer.html
<!-- Footer -->
<footer class="w3-center w3-light-grey w3-padding-12">
    <p>GitHub: <a href="https://github.com/arsalananwar11/Live-Flash-Auctioning-System" title="github" target="_blank" class="w3-hover-text-green">Live Flash Auctioning System</a></p>
</footer>

app/templates/shared/main.html
<!DOCTYPE html>
<html>
    <head>
    <title>Live Flash Auctioning System</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    
    </head>
    <body>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

        <!-- Navbar (top bar) -->
        {% block page_header %}
        {% include "shared/navbar.html" %}
        {% endblock %}

        <!-- Main Body Content -->
        {% block page_body %} 
        {% endblock %}

        <!-- Footer -->
        {% block page_footer %}
        {% include "shared/footer.html" %}
        {% endblock %}
    </body>
</html>

app/templates/shared/navbar.html
<!-- Navbar (top bar) -->
<div class="w3-top">
    <div class="w3-bar w3-white w3-padding w3-card" style="letter-spacing:4px;">
        <a href="/dashboard" class="w3-bar-item w3-button">Flash Bids: Live Flash Auctioning System</a>
        <div class="w3-right w3-hide-small">
            {% if current_user.is_authenticated %}
                <a href="/dashboard" class="w3-bar-item w3-button">Dashboard</a>
                <a href="#" class="w3-bar-item w3-button">Profile</a>
                <a href="{{ url_for('login_controller.logout')}}" class="w3-bar-item w3-button">Logout</a>
            {% else %}
                <a href="{{ url_for('login_controller.login')}}" class="w3-bar-item w3-button">Login</a>
            {% endif %}
        </div>
    </div>
</div>